language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
  matrix:
    - OPTIONAL=true
    - OPTIONAL=false

script:
  - if [ "$OPTIONAL" ]; then
    cargo build --features 'datasets' --verbose;
  else
    cargo build --verbose;
  fi
  - cargo test --verbose
  - cargo build --features stats
  - cargo test --features stats
